CREATE TABLE `LOGN_T_USR` (
  `LOGN_T_USR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOGN_T_USR_NAME` varchar(100) DEFAULT NULL,
  `LOGN_T_USR_SURNAME` varchar(45) DEFAULT NULL,
  `LOGN_T_USR_ACTIVE` char(1) DEFAULT NULL,
  `LOGN_T_USR_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`LOGN_T_USR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Table for user authenfication';
