
  `LOGN_T_PROFILE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK runing nummber',
  `LOGN_T_USER_ID` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_PASSWORD` varchar(20) DEFAULT NULL,
  `LOGN_T_ROLE_ID` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_EMAIL` varchar(45) DEFAULT NULL,
  `LOGN_T_PROFILE_PHONE` varchar(45) DEFAULT NULL,
  `LOGN_T_SITE_ID` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_POSITION` varchar(45) DEFAULT NULL,
  `LOGN_T_PROFILE_CREATEDBY` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_DATE` datetime DEFAULT NULL,
  `LOGN_T_PROFILE_DATETIMESTMP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`LOGN_T_PROFILE_ID`),
  UNIQUE KEY `indexpri` (`LOGN_T_PROFILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Table for Profile and other detail';
CREATE TABLE `LOGN_T_PROFILE` (
  `LOGN_T_PROFILE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK runing nummber',
  `LOGN_T_USR_ID` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_PASSWORD` varchar(20) DEFAULT NULL,
  `LOGN_T_ROLE_ID` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_EMAIL` varchar(45) DEFAULT NULL,
  `LOGN_T_PROFILE_PHONE` varchar(45) DEFAULT NULL,
  `LOGN_T_SITE_ID` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_POSITION` varchar(45) DEFAULT NULL,
  `LOGN_T_PROFILE_CREATEDBY` int(11) DEFAULT NULL,
  `LOGN_T_PROFILE_DATE` datetime DEFAULT NULL,
  `LOGN_T_PROFILE_DATETIMESTMP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`LOGN_T_PROFILE_ID`),
  UNIQUE KEY `indexpri` (`LOGN_T_PROFILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Table for Profile and other detail';
